const products = [
  {id:'gojo-satoru',name:'Gojo Satoru',series:'Jujutsu Kaisen',character:'Gojo Satoru',manufacturer:'Banpresto',condition:'Nueva / caja original',origin:'Japón',description:'Figura de colección seleccionada para Anime no Sekai. Fotografías e información de demostración mientras conectamos el catálogo real.',price:1000,sale:700,status:'Disponible',img:'https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?auto=format&fit=crop&w=900&q=80'},
  {id:'luffy',name:'Monkey D. Luffy',series:'One Piece',character:'Monkey D. Luffy',manufacturer:'Bandai Spirits',condition:'Nueva / caja original',origin:'Japón',description:'Figura de colección de One Piece. Esta ficha sirve como demostración de la vista de detalle antes de cargar tus productos reales.',price:1450,status:'Disponible',img:'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=900&q=80'},
  {id:'tanjiro',name:'Tanjiro Kamado',series:'Demon Slayer',character:'Tanjiro Kamado',manufacturer:'SEGA',condition:'Nueva / caja original',origin:'Japón',description:'Figura de colección de Demon Slayer importada desde Japón. Datos de demostración para validar el diseño del catálogo.',price:1200,sale:990,status:'Disponible',img:'https://images.unsplash.com/photo-1560972550-aba3456b5564?auto=format&fit=crop&w=900&q=80'},
  {id:'goku',name:'Goku',series:'Dragon Ball',character:'Son Goku',manufacturer:'Banpresto',condition:'Nueva / caja original',origin:'Japón',description:'Figura de colección de Dragon Ball. Actualmente aparece como apartada para mostrar cómo cambia la acción comercial según disponibilidad.',price:1650,status:'Apartada',img:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=900&q=80'}
];
const money = n => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
const icon = (name) => ({search:'⌕',menu:'☰',arrow:'›',fire:'🔥',truck:'✈',shield:'✓',chat:'◉',sparkle:'✦'})[name] || '';
function productCard(p){
 const pct=p.sale?Math.round((1-p.sale/p.price)*100):null;
 const action = p.status==='Apartada' ? {text:'Consultar disponibilidad', cls:'disabled', msg:`Hola, vi la figura ${p.name} de ${p.series} como apartada en Anime no Sekai. ¿Podrías avisarme si vuelve a estar disponible?`} : p.status==='Próximamente' ? {text:'Avísame cuando llegue', cls:'notify', msg:`Hola, me interesa la figura ${p.name} de ${p.series}. ¿Podrías avisarme cuando llegue a Anime no Sekai?`} : p.status==='Vendida' ? {text:'¿Puedes conseguirme una?', cls:'sold', msg:`Hola, vi la figura ${p.name} de ${p.series} en Anime no Sekai. ¿Podrías conseguirme una?`} : {text:'Apartar por WhatsApp', cls:'', msg:`Hola, me interesa la figura ${p.name} de ${p.series} que vi en Anime no Sekai. ¿Sigue disponible?`};
 const wa=`https://wa.me/529994739090?text=${encodeURIComponent(action.msg)}`;
 return `<article class="card"><div class="photo"><img src="${p.img}" alt="${p.name}">${pct?`<span class="discount">-${pct}%</span>`:''}<span class="status ${p.status==='Apartada'?'hold':''}">${p.status}</span></div><div class="cardBody"><p class="series">${p.series}</p><h3>${p.name}</h3><div class="prices">${p.sale?`<span class="old">${money(p.price)}</span>`:''}<strong>${money(p.sale||p.price)}</strong></div><button class="details" data-product="${p.id}" type="button">Ver detalles <span>${icon('arrow')}</span></button><a class="whatsapp ${action.cls}" href="${wa}" target="_blank" rel="noopener">${icon('chat')} ${action.text}</a></div></article>`;
}
document.getElementById('app').innerHTML=`
<header><a class="brand" href="#"><span class="mark">界</span><span>ANIME NO <b>SEKAI</b><small>FIGURAS & COLECCIONABLES</small></span></a><nav><a href="#catalogo">Figuras</a><a href="#ofertas">Ofertas</a><a href="#proximamente">Próximamente</a></nav><div class="headActions"><button aria-label="Buscar">${icon('search')}</button><button class="menu" aria-label="Menú">${icon('menu')}</button></div></header>
<main><section class="hero"><div class="heroContent"><span class="eyebrow">${icon('sparkle')} DIRECTO DESDE JAPÓN</span><h1>Tu mundo de<br><em>figuras y coleccionables.</em></h1><p>Encuentra esa pieza que falta en tu colección. Figuras seleccionadas, disponibilidad real y atención directa por WhatsApp.</p><div class="heroBtns"><a href="#catalogo" class="primary">Explorar figuras ${icon('arrow')}</a><a href="#ofertas" class="secondary">${icon('fire')} Ver ofertas</a></div></div><div class="japan">日本<br><span>の世界</span></div></section>
<section class="benefits"><div><span class="featureIcon">${icon('truck')}</span><span><b>Importadas de Japón</b><small>Piezas seleccionadas</small></span></div><div><span class="featureIcon">${icon('shield')}</span><span><b>Compra con confianza</b><small>Atención directa</small></span></div><div><span class="featureIcon">${icon('chat')}</span><span><b>Apártala por WhatsApp</b><small>Rápido y sencillo</small></span></div></section>
<section id="ofertas" class="section"><div class="sectionHead"><div><span class="kicker">🔥 PRECIOS ESPECIALES</span><h2>Ofertas del Sekai</h2></div><a href="#catalogo">Ver todas ${icon('arrow')}</a></div><div class="grid">${products.filter(x=>x.sale).map(productCard).join('')}</div></section>
<section id="catalogo" class="section"><div class="sectionHead"><div><span class="kicker">COLECCIÓN</span><h2>Figuras destacadas</h2></div></div><div class="chips"><button class="active">Todas</button><button>One Piece</button><button>Dragon Ball</button><button>Jujutsu Kaisen</button><button>Demon Slayer</button></div><div class="grid">${products.map(productCard).join('')}</div></section>
<section id="proximamente" class="arrival"><div><span class="kicker">PRÓXIMAMENTE 🇯🇵</span><h2>Nuevas piezas vienen en camino.</h2><p>Descubre próximas importaciones y pregunta por disponibilidad antes de que lleguen.</p></div><a class="primary" href="https://wa.me/529994739090" target="_blank" rel="noopener">Preguntar por WhatsApp</a></section></main>
<footer><div class="brand"><span class="mark">界</span><span>ANIME NO <b>SEKAI</b></span></div><p>Tu mundo de figuras y coleccionables.</p><small>© 2026 Anime no Sekai</small></footer>`;


function productAction(p){
  return p.status==='Apartada' ? {text:'Consultar disponibilidad', cls:'disabled', msg:`Hola, vi la figura ${p.name} de ${p.series} como apartada en Anime no Sekai. ¿Podrías avisarme si vuelve a estar disponible?`} : p.status==='Próximamente' ? {text:'Avísame cuando llegue', cls:'notify', msg:`Hola, me interesa la figura ${p.name} de ${p.series}. ¿Podrías avisarme cuando llegue a Anime no Sekai?`} : p.status==='Vendida' ? {text:'¿Puedes conseguirme una?', cls:'sold', msg:`Hola, vi la figura ${p.name} de ${p.series} en Anime no Sekai. ¿Podrías conseguirme una?`} : {text:'Apartar por WhatsApp', cls:'', msg:`Hola, me interesa la figura ${p.name} de ${p.series} que vi en Anime no Sekai. ¿Sigue disponible?`};
}
function openDetail(id){
  const p=products.find(x=>x.id===id); if(!p)return;
  const pct=p.sale?Math.round((1-p.sale/p.price)*100):null;
  const action=productAction(p);
  const wa=`https://wa.me/529994739090?text=${encodeURIComponent(action.msg)}`;
  const gallery=[p.img,p.img,p.img,p.img];
  const detail=document.createElement('section');
  detail.className='detailView'; detail.id='detailView';
  detail.innerHTML=`<div class="detailTop"><button class="backBtn" type="button">‹ Volver al catálogo</button><button class="detailClose" type="button" aria-label="Cerrar">×</button></div><div class="detailShell"><div class="detailGallery"><div class="detailMainPhoto"><img id="detailMainImage" src="${p.img}" alt="${p.name}"></div><div class="detailThumbs">${gallery.map((img,i)=>`<button class="detailThumb ${i===0?'active':''}" type="button" data-img="${img}"><img src="${img}" alt="Vista ${i+1} de ${p.name}"></button>`).join('')}</div></div><div class="detailInfo"><p class="series">${p.series}</p><h1>${p.name}</h1><div class="detailBadges">${pct?`<span class="detailBadge sale">-${pct}%</span>`:''}<span class="detailBadge ${p.status==='Apartada'?'hold':''}">${p.status}</span></div><div class="detailPrice">${p.sale?`<span class="old">Antes ${money(p.price)}</span>`:''}<strong>${money(p.sale||p.price)}</strong></div><p>${p.description}</p><div class="detailMeta"><div><small>Personaje</small><b>${p.character}</b></div><div><small>Franquicia</small><b>${p.series}</b></div><div><small>Fabricante</small><b>${p.manufacturer}</b></div><div><small>Condición</small><b>${p.condition}</b></div><div><small>Procedencia</small><b>${p.origin}</b></div><div><small>Entrega</small><b>A convenir</b></div></div><div class="detailActions"><a class="whatsapp ${action.cls}" href="${wa}" target="_blank" rel="noopener">${icon('chat')} ${action.text}</a><p class="detailNote">La compra y entrega se acuerdan directamente por WhatsApp.</p></div></div></div>`;
  document.body.appendChild(detail); document.body.classList.add('detail-open');
  detail.querySelectorAll('.backBtn,.detailClose').forEach(b=>b.addEventListener('click',closeDetail));
  detail.querySelectorAll('.detailThumb').forEach(t=>t.addEventListener('click',()=>{detail.querySelector('#detailMainImage').src=t.dataset.img;detail.querySelectorAll('.detailThumb').forEach(x=>x.classList.remove('active'));t.classList.add('active')}));
  history.pushState({detail:id},'',`#figura=${id}`);
}
function closeDetail(){const d=document.getElementById('detailView');if(d)d.remove();document.body.classList.remove('detail-open');if(location.hash.startsWith('#figura='))history.replaceState({},'',location.pathname+location.search+'#catalogo')}
document.addEventListener('click',e=>{const btn=e.target.closest('.details[data-product]');if(btn)openDetail(btn.dataset.product)});
window.addEventListener('popstate',()=>{if(!location.hash.startsWith('#figura=')){const d=document.getElementById('detailView');if(d){d.remove();document.body.classList.remove('detail-open')}}});
if(location.hash.startsWith('#figura=')){setTimeout(()=>openDetail(location.hash.split('=')[1]),0)}
