const products = [
  {name:'Gojo Satoru',series:'Jujutsu Kaisen',price:1000,sale:700,status:'Disponible',img:'https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?auto=format&fit=crop&w=900&q=80'},
  {name:'Monkey D. Luffy',series:'One Piece',price:1450,status:'Disponible',img:'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=900&q=80'},
  {name:'Tanjiro Kamado',series:'Demon Slayer',price:1200,sale:990,status:'Disponible',img:'https://images.unsplash.com/photo-1560972550-aba3456b5564?auto=format&fit=crop&w=900&q=80'},
  {name:'Goku',series:'Dragon Ball',price:1650,status:'Apartada',img:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=900&q=80'}
];
const money = n => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
const icon = (name) => ({search:'⌕',menu:'☰',arrow:'›',fire:'🔥',truck:'✈',shield:'✓',chat:'◉',sparkle:'✦'})[name] || '';
function productCard(p){
 const pct=p.sale?Math.round((1-p.sale/p.price)*100):null;
 const action = p.status==='Apartada' ? {text:'Consultar disponibilidad', cls:'disabled', msg:`Hola, vi la figura ${p.name} de ${p.series} como apartada en Anime no Sekai. ¿Podrías avisarme si vuelve a estar disponible?`} : p.status==='Próximamente' ? {text:'Avísame cuando llegue', cls:'notify', msg:`Hola, me interesa la figura ${p.name} de ${p.series}. ¿Podrías avisarme cuando llegue a Anime no Sekai?`} : p.status==='Vendida' ? {text:'¿Puedes conseguirme una?', cls:'sold', msg:`Hola, vi la figura ${p.name} de ${p.series} en Anime no Sekai. ¿Podrías conseguirme una?`} : {text:'Apartar por WhatsApp', cls:'', msg:`Hola, me interesa la figura ${p.name} de ${p.series} que vi en Anime no Sekai. ¿Sigue disponible?`};
 const wa=`https://wa.me/529994739090?text=${encodeURIComponent(action.msg)}`;
 return `<article class="card"><div class="photo"><img src="${p.img}" alt="${p.name}">${pct?`<span class="discount">-${pct}%</span>`:''}<span class="status ${p.status==='Apartada'?'hold':''}">${p.status}</span></div><div class="cardBody"><p class="series">${p.series}</p><h3>${p.name}</h3><div class="prices">${p.sale?`<span class="old">${money(p.price)}</span>`:''}<strong>${money(p.sale||p.price)}</strong></div><button class="details">Ver detalles <span>${icon('arrow')}</span></button><a class="whatsapp ${action.cls}" href="${wa}" target="_blank" rel="noopener">${icon('chat')} ${action.text}</a></div></article>`;
}
document.getElementById('app').innerHTML=`
<header><a class="brand" href="#"><span class="mark">界</span><span>ANIME NO <b>SEKAI</b><small>FIGURAS & COLECCIONABLES</small></span></a><nav><a href="#catalogo">Figuras</a><a href="#ofertas">Ofertas</a><a href="#proximamente">Próximamente</a></nav><div class="headActions"><button aria-label="Buscar">${icon('search')}</button><button class="menu" aria-label="Menú">${icon('menu')}</button></div></header>
<main><section class="hero"><div class="heroContent"><span class="eyebrow">${icon('sparkle')} DIRECTO DESDE JAPÓN</span><h1>Tu mundo de<br><em>figuras y coleccionables.</em></h1><p>Encuentra esa pieza que falta en tu colección. Figuras seleccionadas, disponibilidad real y atención directa por WhatsApp.</p><div class="heroBtns"><a href="#catalogo" class="primary">Explorar figuras ${icon('arrow')}</a><a href="#ofertas" class="secondary">${icon('fire')} Ver ofertas</a></div></div><div class="japan">日本<br><span>の世界</span></div></section>
<section class="benefits"><div><span class="featureIcon">${icon('truck')}</span><span><b>Importadas de Japón</b><small>Piezas seleccionadas</small></span></div><div><span class="featureIcon">${icon('shield')}</span><span><b>Compra con confianza</b><small>Atención directa</small></span></div><div><span class="featureIcon">${icon('chat')}</span><span><b>Apártala por WhatsApp</b><small>Rápido y sencillo</small></span></div></section>
<section id="ofertas" class="section"><div class="sectionHead"><div><span class="kicker">🔥 PRECIOS ESPECIALES</span><h2>Ofertas del Sekai</h2></div><a href="#catalogo">Ver todas ${icon('arrow')}</a></div><div class="grid">${products.filter(x=>x.sale).map(productCard).join('')}</div></section>
<section id="catalogo" class="section"><div class="sectionHead"><div><span class="kicker">COLECCIÓN</span><h2>Figuras destacadas</h2></div></div><div class="chips"><button class="active">Todas</button><button>One Piece</button><button>Dragon Ball</button><button>Jujutsu Kaisen</button><button>Demon Slayer</button></div><div class="grid">${products.map(productCard).join('')}</div></section>
<section id="proximamente" class="arrival"><div><span class="kicker">PRÓXIMAMENTE 🇯🇵</span><h2>Nuevas piezas vienen en camino.</h2><p>Descubre próximas importaciones y pregunta por disponibilidad antes de que lleguen.</p></div><a class="primary" href="https://wa.me/529994739090" target="_blank" rel="noopener">Preguntar por WhatsApp</a></section></main>
<footer><div class="brand"><span class="mark">界</span><span>ANIME NO <b>SEKAI</b></span></div><p>Tu mundo de figuras y coleccionables.</p><small>© 2026 Anime no Sekai</small></footer>`;
