import React from 'react';import{createRoot}from'react-dom/client';import{Search,Menu,MessageCircle,ChevronRight,Flame,Truck,ShieldCheck,Sparkles}from'lucide-react';import'./styles.css';
const products=[
{name:'Gojo Satoru',series:'Jujutsu Kaisen',price:1000,sale:700,status:'Disponible',img:'https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?auto=format&fit=crop&w=900&q=80'},
{name:'Monkey D. Luffy',series:'One Piece',price:1450,status:'Disponible',img:'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=900&q=80'},
{name:'Tanjiro Kamado',series:'Demon Slayer',price:1200,sale:990,status:'Disponible',img:'https://images.unsplash.com/photo-1560972550-aba3456b5564?auto=format&fit=crop&w=900&q=80'},
{name:'Goku',series:'Dragon Ball',price:1650,status:'Apartada',img:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=900&q=80'}];
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
function Product({p}){const pct=p.sale?Math.round((1-p.sale/p.price)*100):null;const wa=`https://wa.me/529994739090?text=${encodeURIComponent(`Hola, me interesa la figura ${p.name} de ${p.series} que vi en Anime no Sekai. ¿Sigue disponible?`)}`;return <article className="card"><div className="photo"><img src={p.img} alt={p.name}/>{pct&&<span className="discount">-{pct}%</span>}<span className={`status ${p.status==='Apartada'?'hold':''}`}>{p.status}</span></div><div className="cardBody"><p className="series">{p.series}</p><h3>{p.name}</h3><div className="prices">{p.sale&&<span className="old">{money(p.price)}</span>}<strong>{money(p.sale||p.price)}</strong></div><button className="details">Ver detalles <ChevronRight size={16}/></button><a className="whatsapp" href={wa} target="_blank"><MessageCircle size={18}/> Apartar por WhatsApp</a></div></article>}
function App(){return <><header><a className="brand" href="#"><span className="mark">界</span><span>ANIME NO <b>SEKAI</b><small>FIGURAS & COLECCIONABLES</small></span></a><nav><a href="#catalogo">Figuras</a><a href="#ofertas">Ofertas</a><a href="#proximamente">Próximamente</a></nav><div className="headActions"><button aria-label="Buscar"><Search/></button><button className="menu" aria-label="Menú"><Menu/></button></div></header><main><section className="hero"><div className="heroGlow"></div><div className="heroContent"><span className="eyebrow"><Sparkles size={15}/> DIRECTO DESDE JAPÓN</span><h1>Tu mundo de<br/><em>figuras y coleccionables.</em></h1><p>Encuentra esa pieza que falta en tu colección. Figuras seleccionadas, disponibilidad real y atención directa por WhatsApp.</p><div className="heroBtns"><a href="#catalogo" className="primary">Explorar figuras <ChevronRight size={18}/></a><a href="#ofertas" className="secondary"><Flame size={18}/> Ver ofertas</a></div></div><div className="japan">日本<br/><span>の世界</span></div></section><section className="benefits"><div><Truck/><span><b>Importadas de Japón</b><small>Piezas seleccionadas</small></span></div><div><ShieldCheck/><span><b>Compra con confianza</b><small>Atención directa</small></span></div><div><MessageCircle/><span><b>Apártala por WhatsApp</b><small>Rápido y sencillo</small></span></div></section><section id="ofertas" className="section"><div className="sectionHead"><div><span className="kicker">🔥 PRECIOS ESPECIALES</span><h2>Ofertas del Sekai</h2></div><a href="#catalogo">Ver todas <ChevronRight size={16}/></a></div><div className="grid">{products.filter(x=>x.sale).map(p=><Product key={p.name} p={p}/>)}</div></section><section id="catalogo" className="section"><div className="sectionHead"><div><span className="kicker">COLECCIÓN</span><h2>Figuras destacadas</h2></div></div><div className="chips"><button className="active">Todas</button><button>One Piece</button><button>Dragon Ball</button><button>Jujutsu Kaisen</button><button>Demon Slayer</button></div><div className="grid">{products.map(p=><Product key={p.name} p={p}/>)}</div></section><section id="proximamente" className="arrival"><div><span className="kicker">PRÓXIMAMENTE 🇯🇵</span><h2>Nuevas piezas vienen en camino.</h2><p>Descubre próximas importaciones y pregunta por disponibilidad antes de que lleguen.</p></div><a className="primary" href="https://wa.me/529994739090" target="_blank">Preguntar por WhatsApp</a></section></main><footer><div className="brand"><span className="mark">界</span><span>ANIME NO <b>SEKAI</b></span></div><p>Tu mundo de figuras y coleccionables.</p><small>© 2026 Anime no Sekai</small></footer></>};createRoot(document.getElementById('root')).render(<App/>);
